import itertools

import rus2jap

def all_registers(s):
    for p in itertools.product(*zip(*[s, s.swapcase()])):
        yield "".join(p)

rus2jap.load_conv_tab()
rus2jap.load_jap_tab()

hira_out = open("rus2hira.tab", "w")
kana_out = open("rus2kana.tab", "w")

print ("# Autogenerated", file=hira_out)
print ("# Autogenerated", file=kana_out)

for src, conv in rus2jap.conv_tab.items():
    for p in all_registers(src):
        print (src, p)
        hira = rus2jap.rus2jap(src, "hiragana")
        if not hira: hira = "!"
        kana = rus2jap.rus2jap(src, "katakana")
        if not kana: kana = "!"
        print (f"{p} {hira}", file=hira_out)
        print (f"{p} {kana}", file=kana_out)
